jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      name: Set up Java 19
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19
    - continue-on-error: true
      name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-includes: 'caches

          notifications

          jdks

          ${{ github.workspace }}/.gradle/configuration-cache

          '
    - continue-on-error: true
      name: Change wrapper permissions
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Build apk debug
      run: ./gradlew app:assembleDefaultDebug
    - continue-on-error: true
      name: Build apk fdroid-debug
      run: ./gradlew app:assembleFdroidDebug
    - continue-on-error: true
      name: Upload FoxMMM-default-arm64-v8a-debug
      uses: actions/upload-artifact@v3
      with:
        name: FoxMMM-default-arm64-v8a-debug
        path: app/build/outputs/apk/default/debug/*-default-arm64-v8a-debug.apk
    - continue-on-error: true
      name: Upload FoxMMM-default-armeabi-v7a-debug
      uses: actions/upload-artifact@v3
      with:
        name: FoxMMM-default-armeabi-v7a-debug
        path: app/build/outputs/apk/default/debug/*-default-armeabi-v7a-debug.apk
    - continue-on-error: true
      name: Upload FoxMMM-default-universal-debug
      uses: actions/upload-artifact@v3
      with:
        name: FoxMMM-default-universal-debug
        path: app/build/outputs/apk/default/debug/*-default-universal-debug.apk
    - continue-on-error: true
      name: Upload FoxMMM-default-x86-debug
      uses: actions/upload-artifact@v3
      with:
        name: FoxMMM-default-x86-debug
        path: app/build/outputs/apk/default/debug/*-default-x86-debug.apk
    - continue-on-error: true
      name: Upload FoxMMM-default-x86_64-debug
      uses: actions/upload-artifact@v3
      with:
        name: FoxMMM-default-x86_64-debug
        path: app/build/outputs/apk/default/debug/*-default-x86_64-debug.apk
name: Generate APK Debug
on:
  repository_dispatch:
    types: trigger-ga___build-debug.yml
