jobs:
  build:
    name: Dependencies
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19
    - continue-on-error: true
      name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Change wrapper permissions
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Run snapshot action
      uses: mikepenz/gradle-dependency-submission@v1
      with:
        gradle-build-module: :app
        gradle-project-path: .
name: Dependencies
on:
  repository_dispatch:
    types: trigger-ga___dependencies.yml
